{
	"_Type": "Action.Type.RestService.SendRequest",
	"Target": {
		"Service": "/FrieghtAppDetail/Services/FrieghtRestSrv.service",
		 "Path": "/updateStatus",
		"RequestProperties": {
			"Method": "POST",
			"Headers": {
                "Accept": "application/json",
                "Content-Type": "application/json"
            },
		  "Body": {
                 "altKey": "/FrieghtAppDetail/Rules/Shipment/ShipmentStatusUpdateAltKey.js",
                 "locationAltKey" : "/FrieghtAppDetail/Rules/Shipment/ShipmentStatusUpdatelocationAltKey.js",
                 "eventName": "/FrieghtAppDetail/Rules/Shipment/ShipmentStatusUpdateEventName.js",
                 "eventTime":"/FrieghtAppDetail/Rules/Shipment/ShipmentStatusUpdateEventTime.js",
                 "eventLong":"/FrieghtAppDetail/Rules/Location/GetLongitude.js",
                 "eventLat": "/FrieghtAppDetail/Rules/Location/GetLatitude.js",
				 "stopId" : "/FrieghtAppDetail/Rules/Shipment/GetStopID.js",
				 "signature":"/FrieghtAppDetail/Rules/ProofOfDelivery/ProofOfDeliveryUpdateSignature.js",
				 "podImage": "/FrieghtAppDetail/Rules/ProofOfDelivery/ProofOfDeliveryUpdateAttachment.js",
				 "timeZone": "/FrieghtAppDetail/Rules/Shipment/GetTimeZone.js"
                }
	},
	"ActionResult": {
		"_Name": "epdResult"
	}
	}
}