{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavToShipmentList"
	},
	"PageToOpen": "/FrieghtAppDetail/Pages/Shipment/FetchShipmentDetails.page",
	"NavigationType": "Inner",
	"ModalPageFullscreen": true
}