{
	"_Type": "Action.Type.RestService.SendRequest",
	"Target": {
		"Service": "/FrieghtAppDetail/Services/FrieghtRestSrv.service",
		 "Path": "/updateDelivery",
		"RequestProperties": {
			"Method": "POST",
			"Headers": {
                "Accept": "application/json",
                "Content-Type": "application/json"
            },
		  "Body": {
                 "FoId": "/FrieghtAppDetail/Rules/ProofOfDelivery/GetShipmentNumForMaterialUpdate.js",
                 "LocationId" : "/FrieghtAppDetail/Rules/ProofOfDelivery/GetLocationIDForMaterialUpdate.js",
                 "ItemNo": "#Control:ItemNo/#Value",
                 "ProductId":"#Control:ProductId/#Value",
                 "ActQty":"#Control:Quantity/#Value"
                }
	},
	"ActionResult": {
		"_Name": "epdResult"
	}
	},
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Posting..",
	"OnSuccess": "/FrieghtAppDetail/Rules/Logging/MaterialFetchOnSuccessfulUpdate.js",
	"OnFailure": "/FrieghtAppDetail/Actions/UpdateFailed.action"
}